### PR TITLE
Show Traffic Lights as default view

### PR DESCRIPTION
**Pull request by hwangist**
Changed activity flow so RoomActivity immediately launches with Traffic
Lights on app start. Traffic Lights now behaves like a “home screen”.

### CODE REVIEW

**Comment by bklang** [comment]
This one doesn't seem to be working for me. Immediately upon launching the app, I'm still going to the old home screen, which is the list of available rooms along with the "Book Now" button (if the room is available).

**Comment by hwangist** [comment]
Oh, I probably should have documented on the GH issue. The app has a notion
of a "favorite room" that needs to be set before automatically going to
traffic lights. Basically, you have to select the room in the Lobby
(available rooms) view first so that it gets set as your favorite. After
that, each time you launch the app, it should go to traffic lights. Let me
know if that works for you. If not, there must be something else going on.

**Comment by hwangist** [comment]
On second thought, favorite room might be in Settings. You may have to specify the default (favorite) room for the traffic lights to work properly. Try that and let me know if it works after relaunch.

**Comment by bklang** [comment]
That does help, yes. After launching it still goes to the room list, but within 20s it goes to the traffic light.  While it still doesn't launch to the traffic light view, this is sufficient for my needs.  Thanks!

**Comment by hwangist** [comment]
I just checked again and it's working for me. After selecting the default room in Settings and relaunching, it goes immediately to the traffic lights for that room. You may need to completely relaunch the app by closing it, clearing it from the recent apps list, then restarting from the app's launcher icon. If that's the reason it didn't work earlier (not completely cleared), it indicates a bug with refreshing app state after Settings change.

**Pull request closed without merging**
