### PR TITLE
Larger time picker buttons

### PR DESCRIPTION
**Pull request by hwangist**
Make plus and minus buttons bigger. Changed units to dp. Set all caps
for start/end labels.

### CODE REVIEW

**Comment by bklang** [comment]
The buttons are much more usable now, but it caused a side effect. See the screenshot:
device-2015-09-08-165836

**Comment by hwangist** [comment]
I'll take a look later tonight. I addressed this problem with the UI changes in https://github.com/bklang/meeting-room-tablet/pull/12

But that may have only applied to the Lobby screen pop-up. I may have to apply those same UI changes to the Calendar View pop-up.

**Comment by bklang** [comment]
Ah, ok. I'll merge this with #12 and see if the problem goes away.

**Comment by hwangist** [comment]
I just verified this is resolved in #12 with those other pop UI changes.

**Pull request closed without merging**
